try(require(shiny)||install.packages("shiny"))
try(require(udpipe)||install.packages("udpipe"))
try(require(ggplot2)||install.packages("ggplot2"))
try(require(igraph)||install.packages("igraph"))
try(require(ggraph)||install.packages("ggraph"))
try(require(wordcloud)||install.packages("wordcloud"))
try(require(dplyr)||install.packages("dplyr"))
try(require(stringr)||install.packages("stringr"))
